/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimpleRouteImport } from './routes/simple'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSimpleDashboardRouteImport } from './routes/_authenticated/simple-dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedHealthInsightsRouteImport } from './routes/_authenticated/health-insights'
import { Route as AuthenticatedFutureMeRouteImport } from './routes/_authenticated/future-me'
import { Route as AuthenticatedEnhancedDashboardRouteImport } from './routes/_authenticated/enhanced-dashboard'
import { Route as AuthenticatedDecisionHubRouteImport } from './routes/_authenticated/decision-hub'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCopilotRouteImport } from './routes/_authenticated/copilot'

const SimpleRoute = SimpleRouteImport.update({
  id: '/simple',
  path: '/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSimpleDashboardRoute =
  AuthenticatedSimpleDashboardRouteImport.update({
    id: '/simple-dashboard',
    path: '/simple-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthInsightsRoute =
  AuthenticatedHealthInsightsRouteImport.update({
    id: '/health-insights',
    path: '/health-insights',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFutureMeRoute = AuthenticatedFutureMeRouteImport.update({
  id: '/future-me',
  path: '/future-me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnhancedDashboardRoute =
  AuthenticatedEnhancedDashboardRouteImport.update({
    id: '/enhanced-dashboard',
    path: '/enhanced-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDecisionHubRoute =
  AuthenticatedDecisionHubRouteImport.update({
    id: '/decision-hub',
    path: '/decision-hub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCopilotRoute = AuthenticatedCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/debug': typeof DebugRoute
  '/simple': typeof SimpleRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/decision-hub': typeof AuthenticatedDecisionHubRoute
  '/enhanced-dashboard': typeof AuthenticatedEnhancedDashboardRoute
  '/future-me': typeof AuthenticatedFutureMeRoute
  '/health-insights': typeof AuthenticatedHealthInsightsRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simple-dashboard': typeof AuthenticatedSimpleDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/debug': typeof DebugRoute
  '/simple': typeof SimpleRoute
  '/copilot': typeof AuthenticatedCopilotRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/decision-hub': typeof AuthenticatedDecisionHubRoute
  '/enhanced-dashboard': typeof AuthenticatedEnhancedDashboardRoute
  '/future-me': typeof AuthenticatedFutureMeRoute
  '/health-insights': typeof AuthenticatedHealthInsightsRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/simple-dashboard': typeof AuthenticatedSimpleDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/debug': typeof DebugRoute
  '/simple': typeof SimpleRoute
  '/_authenticated/copilot': typeof AuthenticatedCopilotRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/decision-hub': typeof AuthenticatedDecisionHubRoute
  '/_authenticated/enhanced-dashboard': typeof AuthenticatedEnhancedDashboardRoute
  '/_authenticated/future-me': typeof AuthenticatedFutureMeRoute
  '/_authenticated/health-insights': typeof AuthenticatedHealthInsightsRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/simple-dashboard': typeof AuthenticatedSimpleDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/debug'
    | '/simple'
    | '/copilot'
    | '/dashboard'
    | '/decision-hub'
    | '/enhanced-dashboard'
    | '/future-me'
    | '/health-insights'
    | '/memory'
    | '/settings'
    | '/simple-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/debug'
    | '/simple'
    | '/copilot'
    | '/dashboard'
    | '/decision-hub'
    | '/enhanced-dashboard'
    | '/future-me'
    | '/health-insights'
    | '/memory'
    | '/settings'
    | '/simple-dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/debug'
    | '/simple'
    | '/_authenticated/copilot'
    | '/_authenticated/dashboard'
    | '/_authenticated/decision-hub'
    | '/_authenticated/enhanced-dashboard'
    | '/_authenticated/future-me'
    | '/_authenticated/health-insights'
    | '/_authenticated/memory'
    | '/_authenticated/settings'
    | '/_authenticated/simple-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DebugRoute: typeof DebugRoute
  SimpleRoute: typeof SimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simple': {
      id: '/simple'
      path: '/simple'
      fullPath: '/simple'
      preLoaderRoute: typeof SimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/simple-dashboard': {
      id: '/_authenticated/simple-dashboard'
      path: '/simple-dashboard'
      fullPath: '/simple-dashboard'
      preLoaderRoute: typeof AuthenticatedSimpleDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health-insights': {
      id: '/_authenticated/health-insights'
      path: '/health-insights'
      fullPath: '/health-insights'
      preLoaderRoute: typeof AuthenticatedHealthInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/future-me': {
      id: '/_authenticated/future-me'
      path: '/future-me'
      fullPath: '/future-me'
      preLoaderRoute: typeof AuthenticatedFutureMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enhanced-dashboard': {
      id: '/_authenticated/enhanced-dashboard'
      path: '/enhanced-dashboard'
      fullPath: '/enhanced-dashboard'
      preLoaderRoute: typeof AuthenticatedEnhancedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decision-hub': {
      id: '/_authenticated/decision-hub'
      path: '/decision-hub'
      fullPath: '/decision-hub'
      preLoaderRoute: typeof AuthenticatedDecisionHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/copilot': {
      id: '/_authenticated/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AuthenticatedCopilotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCopilotRoute: typeof AuthenticatedCopilotRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDecisionHubRoute: typeof AuthenticatedDecisionHubRoute
  AuthenticatedEnhancedDashboardRoute: typeof AuthenticatedEnhancedDashboardRoute
  AuthenticatedFutureMeRoute: typeof AuthenticatedFutureMeRoute
  AuthenticatedHealthInsightsRoute: typeof AuthenticatedHealthInsightsRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSimpleDashboardRoute: typeof AuthenticatedSimpleDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCopilotRoute: AuthenticatedCopilotRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDecisionHubRoute: AuthenticatedDecisionHubRoute,
  AuthenticatedEnhancedDashboardRoute: AuthenticatedEnhancedDashboardRoute,
  AuthenticatedFutureMeRoute: AuthenticatedFutureMeRoute,
  AuthenticatedHealthInsightsRoute: AuthenticatedHealthInsightsRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSimpleDashboardRoute: AuthenticatedSimpleDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DebugRoute: DebugRoute,
  SimpleRoute: SimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
